# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-19 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=30)),
                ('bidded_time', models.TimeField(default=django.utils.timezone.now)),
                ('bidded_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(blank=True, upload_to=b'')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.TimeField(default=datetime.time(2, 0))),
                ('current_bidder', models.CharField(blank=True, max_length=30, null=True)),
                ('currnet_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bidded_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default=b'future', max_length=30)),
                ('no_of_bids', models.IntegerField(null=True)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
