# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aform', '0001_initial'),
        ('aahome1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aform.Seller'),
        ),
        migrations.AddField(
            model_name='p_history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aahome1.Product'),
        ),
    ]
